### ISSUE TITLE
Phantom View Port Size

### ISSUE THREAD

**Issue by C4rl0s** [localnerve/grunt-html-snapshots#11]
I was researching about a possibility to add the viewPortSize feature in to this awesome library or if there is any way to configure it?.

If the choose is the first option how we could contribute?.

Thank you,
Carlos :)

**Comment by localnerve** [comment]
Is `viewPortSize` a PhantomJS option? 
If so, did you try adding to `phantomjsOptions`?
This is documented here: https://github.com/localnerve/html-snapshots#process-control-options.

Probably this issue should be on that repo. This project just organizes options for grunt and runs that lib.

**Comment by localnerve** [comment]
@C4rl0s, Haven't heard back in 20 days. Closing. Please reopen if you want to continue this conversation.
