### ISSUE TITLE
Error in generating snapshot for home page

### ISSUE THREAD

**Issue by CloudHadoop** [localnerve/grunt-html-snapshots#4]
My app is SPA angularjs
Here is my grunt file 
html_snapshots: {// options for all targets
        options: {
            input: "sitemap",
          source: "http://localhost/sitemap.xml",
          hostname: "localhost",
          selector: "body",
          //selector: { "__default": "body", "/#!": "#home-content" },
          outputDirClean: true,
          phantomjs: "/usr/bin/phantomjs",
          useJQuery:false,
          timeout: 200000,
          phantomjsOptions:["--load-images=false", "--ignore-ssl-errors=true"]
        },

Here are my urls to my site
1.localhost/#/ -
2.localhost/#/page1
3.localhost/#/page2

grunt generate pages for 2 and 3 urls. but for 1 it is generating the html file as below
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"><html><head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
<title>ERROR: The requested URL could not be retrieved</title> <style type="text/css"><!--   /*

please let me know if you need more details

**Comment by localnerve** [comment]
My first deductions:
1. Hash URL working, since it gets the two other pages.
2. Hash routes are client side routes of the / page.
.*. Possibly something up with `#/` client side route.

Questions:
1. What happens if you go to url `localhost/#/` from a regular browser? 
2. What happens if you just use `localhost/` for the home page? (that's how people will arrive on your site, right?)

**Comment by CloudHadoop** [comment]
Thanks for the reply
sorry for the confusion. Please read "localhost/#/"  as "localhost/#!/"

Answers for your questions
1. - is mistakenly typed
2  localhost/#!/ correctly loads home page of my site ie
3. localhost/ also behave same as above 2 and url changes to  localhost/#!/

**Comment by localnerve** [comment]
Ok, is this solved then? Can close?

**Comment by CloudHadoop** [comment]
Issue not yet solved.

Regular brower it is working for all urls.

When we run grunt command, "localhost/#!/" is not generating html snapshot, but other urls "localhost/#!/page1" and "localhost/#!/page2" generates html snapshots correctly

**Comment by localnerve** [comment]
Is there a public endpoint I can run this against to reproduce?

Why can't you use `/` for the home page?

**Comment by localnerve** [comment]
Closing for no response. Feel free to re open if you want assistance
